apiVersion: v 1
kind: ReplicationController
metadata:
  name: example-rc
spec:
  replicas: 3
  selector:
    app: example-app
    #template is exactly the same as the pod manifest file (except api version and kind)
  template:
    metadata:
      name: example-pod
      labels:
        app: example-app
    spec:
      containers:
        - name: example-container
          image: example
          ports:
            - containerPort: 80